openai:
  chatgtp:
    api:
      key: 
      url: https://api.openai.com/v1/chat/completions
    max-completions: 1
    max_tokens: 100
    model: gpt-3.5-turbo
    temperature: 0

    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driverclass: org.h2.Driver
      jpa:
        hibernate:
          ddl-auto: update
      h2:
        console.enabled: true